apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
        - name: student-app
          image: student-app:latest
          ports:
            - containerPort: 8089
