apiVersion: v1
kind: Service
metadata:
  name: student-deployment
spec:
  type: NodePort
  selector:
    app: student
  ports:
    - port: 80          # external port
      targetPort: 8089  # Spring Boot internal port
