apiVersion: v1
kind: Pod
metadata:
  name: student-pod
  labels:
    app: student-management
spec:
  containers:
    - name: student-app
      image: taiebbelhadjali/pipeline:v1.0
      ports:
        - containerPort: 8080
